# Generated by Django 5.0.7 on 2024-08-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='pic',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
